### ISSUE TITLE
Beaglebone Black - Buildroot (No hdmi output)

### ISSUE THREAD

**Issue by erakis** [beagleboard/buildroot-old#1]
Hi,

I recently build a Linux Image for the Beaglebone Black rev.C. I cannot get working the hdmi output with this buildroot image. If I use the stock image coming on the NAND of the beaglebone, the hdmi output is well working so this is not an hardware failure. 

I need an image having a minimal footprint having (Qt5, nodejs, systemd, nano, some other small packages).

Here is what I've done to build the image on buildroot : 

   $ make beaglebone_defconfig
   $ make menuconfig 

I add some missing package (ti-gfx, glibc, etc...) and I build the image using :

   $ make

I then prepared the MicroSDCard :

   $ sudo mount /dev/sdf1 /media/boot 
   $ sudo mount /dev/sdf2 /media/rootfs 
   $ sudo cp MLO u-boot.img zImage uEnv.txt *.dtb /media/boot
   $ sudo dd if=rootfs.ext2 of=/dev/sdf2
   $ sudo umount /dev/sdf1 
   $ sudo umount /dev/sdf2 

I insert the MicrosSDCard into the BeagleBone, hold the S2 button down and then wait until the beaglebone boot. Notice that I have an HDMI LG 24'' monitor connected to the beaglebone and also the console (FTDI) to my Windows computer (putty).

The monitor remain always blank, the beaglebone do not output on.

Someone on buildroot give me a patch to allow tilcdc to be selected in the kernel. I applied this patch. (Patch of tilcdc).

I rebuild the kernel :

   $ make linix-dirclean
   $ make kernel
   $ make

Copy the new kernel to the SDCard, and also the rootfs (just to be sure). But the same problem, no hdmi output !

While looking to the dmesg, I notice this error : 

   [    1.402202] tilcdc 4830e000.lcdc: no encoders/connectors found
   [    1.408337] tilcdc 4830e000.lcdc: failed to initialize mode setting

I also tried modifying the uEnv.txt and setting parameters found on internet but same blank screen. 

Now I'm very out of idea :(

Is somebody have succeed to get hdmi working using a buildroot image ? The guys on IRC assumed that the Buildroot configuration for the beaglebone black may be too old and need to be updated.

From the Buildroot configuration for Beaglebone Black (beaglebone_defconfig) the kernel is take from the TI repository, could we point it to the one from Nelson here ? Could it be related to my hdmi problem ?

If we find the solution together it is the whole community that will benefit, since I do not seem to be the only person who wants to use Buildroot with Beaglebone :)

Best regards,
Martin

**Comment by jadonk** [comment]
This is pretty old. I've started doing new buildroot builds on the beagle-tester branch using the pocketbeagle_defconfig. Let me know if you have issues with that one and re-open this.
